### ISSUE TITLE
ParameterList fails to parse filename from Content-Disposition header encoded in UTF-8 with Q encoding

### ISSUE THREAD

**Issue by Dr4K4n** [jakartaee/mail-api#687]
**Describe the bug**
We are using the mail-api to parse incoming emails (MimeMessages), we received a particular email with a PDF attachment.
The filename of this attachment is encoded in the Content-Disposition header in a "weird" way.
This leads to the following exception

Stacktrace:
```
 Caused by: jakarta.mail.internet.ParseException: In parameter list <;
   filename==?utf-8?Q?XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX--111111111-XXXXXXXXXXXXXXXXXXX?=
   =?utf-8?Q?XXXXXXXXXXXXXXXXXXX=2Epdf?=;
   filename*0*=utf-8''XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX--111111111-XXXXXXXXXXX;
   filename*1*=XXXXXXXXXXXXXXXXXXXXXXXXXXX.pdf>, expected parameter value, got "="
     at jakarta.mail.internet.ParameterList.<init>(ParameterList.java:273)
     at jakarta.mail.internet.ContentDisposition.<init>(ContentDisposition.java:86)
     at jakarta.mail.internet.MimeBodyPart.getDisposition(MimeBodyPart.java:1239)
     at jakarta.mail.internet.MimeBodyPart.getDisposition(MimeBodyPart.java:327)
```

After googling I found that the header is encoded in "Q encoding" (https://en.wikipedia.org/wiki/MIME#Difference_between_Q-encoding_and_quoted-printable) It is also mentioned in RFC2047 (https://www.ietf.org/rfc/rfc2047.txt).
The method jakarta.mail.internet.MimeUtility.decodeText(String etext) is actually able to parse such strings.

**To Reproduce**
See test cases in attached pull request

**Expected behavior**
See test cases in attached pull request

**Envorinment:**
 - Version: 2.0.1

**Comment by lukasj** [comment]
According to [RFC 2231](https://www.rfc-editor.org/rfc/rfc2231) which updates 2047 and explicitly allows using encoding definition in the Content-Disposition header, it is required to inform the client about encoding in parameter value being used through the usage of the `*` in the parameter name (see the definition od _extended-parameter/extended-initial-name_ in the grammar), so in this particular case, the header should look like:

```
filename*==?utf-8?Q?XX...
```
Also would it be possible to share full header for which it fails for you? Thanks

**Comment by piu130** [comment]
We have a similar problem with the following part:
```
---------------------63e19e4de85d1f5438987132a0616d2f
Content-Transfer-Encoding: base64
Content-Type: image/png; filename="=?UTF-8?B?aW1hZ2UwMDEucG5n?="; name="=?U
 TF-8?B?aW1hZ2UwMDEucG5n?="
Content-Disposition: attachment; filename="=?UTF-8?B?aW1hZ2UwMDEucG5n?="; n
 ame="=?UTF-8?B?aW1hZ2UwMDEucG5n?="

<binary>
```
Exception:
```
jakarta.mail.internet.ParseException: In parameter list <; filename="=?UTF-8?B?aW1hZ2UwMDEucG5n?="; n
 ame="=?UTF-8?B?aW1hZ2UwMDEucG5n?=">, expected '=', got "ame"
	at jakarta.mail.internet.ParameterList.<init>(ParameterList.java:255)
	at jakarta.mail.internet.ContentDisposition.<init>(ContentDisposition.java:81)
	at jakarta.mail.internet.MimeBodyPart.getDisposition(MimeBodyPart.java:1219)
	at jakarta.mail.internet.MimeBodyPart.getDisposition(MimeBodyPart.java:325)
```
I assume it's because the header is multiline.
The Java String looks like:
```
attachment; filename="=?UTF-8?B?aW1hZ2UwMDEucG5n?="; n\r\n ame="=?UTF-8?B?aW1hZ2UwMDEucG5n?="
```
